
# need for install
sudo: required

# uses bash v 4.3 form ubuntu 14
language: shell

env: 
  global:
  #
  
cache:
  directories:
    # docker pull cache
    - $HOME/docker
    
services:
  - docker
      
before_install:
  - echo $(id) # verify user
  - echo $HOME # verify home
  - docker --version # verify docker

install:
  #

before_script:
  # provision container
  - build/docker/setup.sh

script: 
  # invoke tests in container
  - build/docker/verify.sh

after_script:
  # session complete
  - echo "done"
